name = floating_candles
title = Floating Candles
description = Support-free candles with light level 14, animated flames and direct placement in air.
author = Jon Ellwood
min_minetest_version = 5.4
supported_games = asuna
